### ISSUE TITLE
Develop a docking station

### ISSUE THREAD

**Issue by TobiasLundby** [RMUASD-Team2-2017/UASD#15]
Research components
Buy components
Construct
Test

**Comment by mhoejgaard** [comment]
The docking station is done but we are waiting for components and connectiors

**Comment by mhoejgaard** [comment]
We don't order the power diodes, as they will require huge cooling plates. Instead we will use the board developed by SDU (if it gets ready).

**Comment by mhoejgaard** [comment]
Postponed until we get the connectors.

**Comment by TobiasLundby** [comment]
We need to order a new balance cable for the 4S batteries

**Comment by tobiasrj20** [comment]
Needs to be tested if the drone can take off from the docking station.

**Comment by tobiasrj20** [comment]
The drone is capable of taking off from the docking station.
