### ISSUE TITLE
Refine path planner node

### ISSUE THREAD

**Issue by bjarkips** [RMUASD-Team2-2017/UASD#39]
Update the path planning algorithm to something more sophisticated.

**Comment by bjarkips** [comment]
Consult team 1 for inspiration.

**Comment by tobiasrj20** [comment]
It is actually made but it needs testing and then implementation of the geofence. Interpolation should also be added. Remember documentation.

**Comment by tobiasrj20** [comment]
The path-planner is working, but does not find the shortest path.
I am currently working on a solution to this. 
It seems like the edge detector is very slow when we have a lot of nodes. Maybe we need to do something about this.
Documentation is still missing.

**Comment by tobiasrj20** [comment]
Pathplanner is finished.
It finds the shortest path. But it needs to be tested in the simulator, can't get that part to work?
Documentation is still missing.

**Comment by tobiasrj20** [comment]
Needs to be tested on the full system
