### ISSUE TITLE
Add sensors to docking station

### ISSUE THREAD

**Issue by bjarkips** [RMUASD-Team2-2017/UASD#40]
Add temperature and humidity sensors to the docking station and update the node to incorporate them.

**Comment by bjarkips** [comment]
Temperature and humidity is probably no longer desired, battery monitoring should, however, be implemented.

**Comment by TobiasLundby** [comment]
We have received temperature and humidity sensors

**Comment by tobiasrj20** [comment]
The temperature and humidity sensor have been interfaced to a raspberry pi 3. 
A python node which publish the temperature and humidity have been implemented and is tested.

**Comment by tobiasrj20** [comment]
Needs to be tested with the full system
