### ISSUE TITLE
Add terminate, abort (return to launch), and land (at current location) to web administration and OES

### ISSUE THREAD

**Issue by mhoejgaard** [RMUASD-Team2-2017/UASD#51]
The OES should just read the gsm_command_queue and act upon it.

**Comment by mhoejgaard** [comment]
They are all added to the OES.

Use caution from now on, as a terminate will disarm the drone in-air!

**Comment by mhoejgaard** [comment]
Land at current location, terminate, return to launch and wait on spot is added as rosservices provided by the drone communication node.

**Comment by TobiasLundby** [comment]
The 3 features (called stopped in my posts) have now been added to the webpage and database. It is implemented such that a request can only be stopped after it has been approved; so alongside the complete option. Therefore as soon as the request has been completed it is not possible, using the UI, to stop the request. The overview of the requests has also been updated such that is has a table for the stopped requests where the stopping reason is also shown.

Specific API for accessing still needs to be made but it is send using the existing API "get_requests" as a field "stopped"

**Comment by TobiasLundby** [comment]
An API has now been made [Wiki link](https://github.com/RMUASD-Team2-2017/UASD/wiki/API#get-request-stop-terminate-abort-land). The API has been tested and works!

A 'pulling' script needs to be made and run on the OES so it can check the state of the request it is flying.

**Comment by mhoejgaard** [comment]
A web interface module has been implemented in the OES. It polls the api at 1 Hz and puts terminate, land, and return to launch commands in the command queue.

**Comment by mhoejgaard** [comment]
Needs to be tested in practice!
