### ISSUE TITLE
Drone mount improvement

### ISSUE THREAD

**Issue by TobiasLundby** [RMUASD-Team2-2017/UASD#64]
The mount underneath the drone should be improved by making it ~1cm shorter (when used with the current legs). 
The AED 'hole' should also be made bigger but since we do not know the dimensions of the AED with pads etc. the supervisor advised to wait with this until he got a complete AED. 
It would make sense to rotate the battery compartments so the batteries are laying instead of standing since it would make the whole mount smaller and then the edge on the bottom of the compartment should be removed in order to make the battery installation easier.

**Comment by tobiasrj20** [comment]
Cleanup the wiring and mount the Raspberry Pi instead of the Toradex board.

**Comment by TobiasLundby** [comment]
All the components have been mounted properly on the drone (except the GPS antennas since we have not gotten the new GPS stands). The NEOPIXELs have been connected to a single UBEC thus having to run them at lower brightness. The Toradex OES has been replaced by the RPi 3 rev B.

**Comment by mhoejgaard** [comment]
We don't have time for this and will accept that the blue bulb touches the ground.
