### ISSUE TITLE
Implement the GCS control node

### ISSUE THREAD

**Issue by bjarkips** [RMUASD-Team2-2017/UASD#7]
Write a functional main function which calls all relevant services and publishes to relevant topics to fully control and monitor the delivery.

**Comment by mhoejgaard** [comment]
Fix eventual problems in other nodes.

**Comment by bjarkips** [comment]
Dummy services, clients and topics have been implemented for docking station, preflight and drone communication nodes.

**Comment by mhoejgaard** [comment]
Still needs implementation of webinteface_node as it is not done yet.
Move to sprint 4

**Comment by mhoejgaard** [comment]
Webnode interface have been implemented.
Current state: Working MVP
* flies whenever a mission is received
* set required states through the webinterface
