### ISSUE TITLE
Make sure SORA is handled correctly in the code

### ISSUE THREAD

**Issue by mhoejgaard** [RMUASD-Team2-2017/UASD#73]
**Mathias needs to implement:**
* **A** Increase gps match threshold distance up to 75 meters (5 seconds, 15 m for each second) **Done**
* **B** 10: Geofence breach: Differ between breach and critical breach (distance to the fence) **Done**
* **C** 13: Make it possible to go from land to loiter **Done**
* **E** Might be missing flight termination from the GCS through user input **Done**

* **F** Make sure the OES parts requiring network does not crash if no network is available. **Partially done**

**Bjarki needs to implement:**
* **D** Implement main link monitoring and GSM failsafes on GCS **Done**
* **G** 1 and 11: GCS should tell the Pixhawk to land via telemetry, if no gsm heartbeat is received within 10 seconds: **Done**
* **H** MAKE SURE ALL TIMEOUTS IN THE CODE MATCHES WITH SORA **Done**

**Check with Tobias:**
* **I** 9: Setup the pixhawk to handle land on the spot if rc is lost for more than 0.5 s

**Comment by mhoejgaard** [comment]
**F**: The webinterface reports that it experiences errors when network is not present but continues when the connection is regained.

It is a major issue that pika does not seem to recover from loss of connection. No solution has been found in pika.

**Comment by mhoejgaard** [comment]
It is a major issue that pika does not seem to recover from loss of connection. No solution has been found in pika.

**Comment by mhoejgaard** [comment]
**E** Flight termination through input is available as terminate.

**Comment by mhoejgaard** [comment]
**C** Fixed with hotfix that toogles loiter when the return to launch button in the webinterface in pushed. It is a hotfix because it does not follow the standard of the node OnboardControl module.

**Comment by mhoejgaard** [comment]
**A**: Added the time difference between the gps fixes to the mismatch calculation based on the SORA description and the implementatition by group 1.

**Comment by mhoejgaard** [comment]
**B**: Added differentitaion of "normal" and critical breach. A critical breach should terminate but this is commented out in OnboardControl for now.

**Comment by bjarkips** [comment]
**G:** ```gcs_control_node``` has been updated to monitor the gsm connection. After 10 seconds of connection loss, if the drone is in the air, ```gcs_control_node``` calls ```/drone_communication/land```. This has been successfully tested in simulation.

**Comment by bjarkips** [comment]
**D, H Done.** See comments on issue #60.

**Comment by bjarkips** [comment]
Current status is good enough for VLOS, this may need reopening for all EVLOS specifications.
